name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Linting
        run: |
          pip install black ruff
          make lint

  Tests:
    needs: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Coverage run pytest
        run: |
          poetry run coverage run --source poetry_plugin_freeze -m pytest tests
          poetry run coverage xml

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v5
        if: contains(matrix.python-version, '3.13') && contains(matrix.os, 'ubuntu')
        with:
          files: ./coverage.xml
          name: codecov
